set nu
set hlsearch
set autoindent
set scrolloff=2
set wildmode=longest,list
set ts=2
set sts=2
set sw=1
set autowrite
set autoread
set cindent
set bs=eol,start,indent
set laststatus=4
set shiftwidth=4
set showmatch
set smartcase
set smarttab
set smartindent
set softtabstop=4
set tabstop=4
set expandtab
set ruler
set incsearch
syntax on
filetype indent plugin on

colorscheme jellybeans
